### ISSUE TITLE
missing pseudochr.fasta.gz for Leishmania in Public server (is Companion still supported)

### ISSUE THREAD

**Issue by rosshandler** [sanger-pathogens/companion#98]
Dear Companion team, 

I would like to use your public server for annotating some assemblies from leishmania that I have generated. However, it seems to me that the server does not actually contain the training sets mentioned in the webpage list. I have use a Leishmania mexicana downloaded from NCBI and the job fails, despite a lot testing of trial and error. The error obtained is the below. I have emailed the contact address given in the website but no one replies. Is it still supported? I appreciate your input.

/www/companion/annot-web/app/workers/hard_worker.rb:34:in `add_result_file': required file not present: /www/companion/annot-web/public/jobs/74f8275b60bbaeba61562e29/pseudochr.fasta.gz (RuntimeError)
	/www/companion/annot-web/app/workers/hard_worker.rb:142:in `perform'
	/www/companion/annot-web/vendor/ruby/2.3.0/gems/sidekiq-4.0.2/lib/sidekiq/processor.rb:150:in `execute_job'
	/www/companion/annot-web/vendor/ruby/2.3.0/gems/sidekiq-4.0.2/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
	/www/companion/annot-web/vendor/ruby/2.3.0/gems/sidekiq-4.0.2/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
	/www/companion/annot-web/vendor/ruby/2.3.0/gems/sidekiq-status-0.6.0/lib/sidekiq-status/server_middleware.rb:37:in `call'
	/www/companion/annot-web/vendor/ruby/2.3.0/gems/sidekiq-4.0.2/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
	/www/companion/annot-web/vendor/ruby/2.3.0/gems/sidekiq-4.0.2/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
	/www/companion/annot-web/vendor/ruby/2.3.0/gems/sidekiq-4.0.2/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
	/www/companion/annot-web/vendor/ruby/2.3.0/gems/sidekiq-4.0.2/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
	/www/companion/annot-web/vendor/ruby/2.3.0/gems/sidekiq-4.0.2/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
	/www/companion/annot-web/vendor/ruby/2.3.0/gems/sidekiq-4.0.2/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
	/www/companion/annot-web/vendor/ruby/2.3.0/gems/sidekiq-4.0.2/lib/sidekiq/logging.rb:30:in `with_context'
	/www/companion/annot-web/vendor/ruby/2.3.0/gems/sidekiq-4.0.2/lib/sidekiq/middleware/server/logging.rb:7:in `call'
	/www/companion/annot-web/vendor/ruby/2.3.0/gems/sidekiq-4.0.2/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
	/www/companion/annot-web/vendor/ruby/2.3.0/gems/sidekiq-4.0.2/lib/sidekiq/middleware/chain.rb:132:in `invoke'
	/www/companion/annot-web/vendor/ruby/2.3.0/gems/sidekiq-4.0.2/lib/sidekiq/processor.rb:127:in `block in process'
	/www/companion/annot-web/vendor/ruby/2.3.0/gems/sidekiq-4.0.2/lib/sidekiq/processor.rb:166:in `stats'
	/www/companion/annot-web/vendor/ruby/2.3.0/gems/sidekiq-4.0.2/lib/sidekiq/processor.rb:126:in `process'
	/www/companion/annot-web/vendor/ruby/2.3.0/gems/sidekiq-4.0.2/lib/sidekiq/processor.rb:79:in `process_one'
	/www/companion/annot-web/vendor/ruby/2.3.0/gems/sidekiq-4.0.2/lib/sidekiq/processor.rb:67:in `run'
	/www/companion/annot-web/vendor/ruby/2.3.0/gems/sidekiq-4.0.2/lib/sidekiq/util.rb:16:in `watchdog'
	/www/companion/annot-web/vendor/ruby/2.3.0/gems/sidekiq-4.0.2/lib/sidekiq/util.rb:24:in `block in safe_thread'

Many thanks,
Ivan

**Comment by janxkoci** [comment]
We have the same issue with Lmex too. Have you found any solution?

I'm thinking about disabling **pseudochromosome contiguation** (in step 5), as that step uses pseudochromosomes, to see if it makes any difference. Have you tried or considered this?

Btw on their [twitter](https://twitter.com/BiottofnI/status/1356159951018848256?s=20) they seem to be looking for programmers.

Thanks for any help.
